name: Issue output for workflow service
on:
  issues:
    types: [opened]

jobs:
  issue-output:
    runs-on: ubuntu-latest
    steps:
        - name: Output issues for workflow service
          run: echo "{{ toJson(github.event) }}"