name: Issue output for workflow service
on:
  issues:
    types: [opened]

jobs:
  issue-output:
    runs-on: ubuntu-latest
    steps:
        - name: Output issue details
          run: echo '{{ toJson(github.event) }}'